// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopEase.API.Data;

#nullable disable

namespace ShopEase.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802182928_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopEase.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInNav")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "🪑",
                            IsActive = true,
                            Name = "Furniture",
                            ShowInNav = true,
                            Slug = "furniture",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "📱",
                            IsActive = true,
                            Name = "Electronics",
                            ShowInNav = true,
                            Slug = "electronics",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "🍳",
                            IsActive = true,
                            Name = "Kitchen",
                            ShowInNav = true,
                            Slug = "kitchen",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "👕",
                            IsActive = true,
                            Name = "Clothes",
                            ShowInNav = true,
                            Slug = "clothes",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "🔧",
                            IsActive = true,
                            Name = "Hardware",
                            ShowInNav = true,
                            Slug = "hardware",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Icon = "⚽",
                            IsActive = true,
                            Name = "Sports",
                            ShowInNav = true,
                            Slug = "sports",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("ShopEase.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gst")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopEase.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShopEase.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Colours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeDelivery")
                        .HasColumnType("bit");

                    b.Property<string>("GstRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeInAiSearch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("LowStockAlert")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mrp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowInDealsStrip")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInFlashSale")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "WoodCraft India",
                            CategoryId = 1,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "Solid oak wood chair with ergonomic backrest.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = true,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 5999m,
                            Name = "Oak Dining Chair — Premium Solid Wood",
                            Price = 3599m,
                            Rating = 4.2000000000000002,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 128,
                            SeoTags = "dining chair, wooden chair, oak, solid wood",
                            ShortDescription = "Premium oak dining chair",
                            ShowInDealsStrip = true,
                            ShowInFlashSale = false,
                            Sku = "WC-CH-001",
                            Status = "Active",
                            Stock = 14,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "ComfortPlus",
                            CategoryId = 1,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "Comfortable 3-seater sofa in premium grey fabric.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = false,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 22000m,
                            Name = "3-Seater Sofa — Grey Fabric",
                            Price = 16999m,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 54,
                            SeoTags = "sofa, 3 seater, grey, fabric, living room",
                            ShortDescription = "3 seater grey sofa",
                            ShowInDealsStrip = false,
                            ShowInFlashSale = false,
                            Sku = "CP-SF-001",
                            Status = "Active",
                            Stock = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "WoodCraft India",
                            CategoryId = 1,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "Natural grain sheesham wood dining table.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = true,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 18000m,
                            Name = "Sheesham Wood Dining Table (4-seater)",
                            Price = 12500m,
                            Rating = 4.5,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 67,
                            SeoTags = "dining table, sheesham, wooden table, 4 seater",
                            ShortDescription = "Sheesham dining table",
                            ShowInDealsStrip = true,
                            ShowInFlashSale = false,
                            Sku = "WC-DT-001",
                            Status = "Active",
                            Stock = 8,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "SoundMax",
                            CategoryId = 2,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "360 degree sound smart speaker with voice control.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = true,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 2499m,
                            Name = "Smart Speaker — 360 Sound",
                            Price = 1299m,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 342,
                            SeoTags = "smart speaker, bluetooth, 360 sound, alexa",
                            ShortDescription = "Smart speaker 360 sound",
                            ShowInDealsStrip = true,
                            ShowInFlashSale = false,
                            Sku = "SM-SP-001",
                            Status = "Active",
                            Stock = 25,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "KitchenPro",
                            CategoryId = 3,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "3 piece non stick pan set for daily cooking.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = false,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 1499m,
                            Name = "Non-stick Pan Set — 3 Piece",
                            Price = 799m,
                            Rating = 4.2999999999999998,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 211,
                            SeoTags = "pan, non stick, cookware, kitchen, set",
                            ShortDescription = "Non stick pan set",
                            ShowInDealsStrip = true,
                            ShowInFlashSale = false,
                            Sku = "KP-PAN-001",
                            Status = "Active",
                            Stock = 30,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "WoodCraft India",
                            CategoryId = 1,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "Walnut finish study table with storage drawer.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = false,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 9999m,
                            Name = "Study Table — Walnut Finish",
                            Price = 6800m,
                            Rating = 4.7000000000000002,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 91,
                            SeoTags = "study table, walnut, desk, wooden table",
                            ShortDescription = "Walnut study table",
                            ShowInDealsStrip = false,
                            ShowInFlashSale = false,
                            Sku = "WC-ST-001",
                            Status = "Active",
                            Stock = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "FabricIndia",
                            CategoryId = 4,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "Premium cotton kurta for daily wear.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = false,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 999m,
                            Name = "Cotton Kurta — Premium",
                            Price = 499m,
                            Rating = 4.0999999999999996,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 87,
                            SeoTags = "kurta, cotton, men, ethnic wear, indian",
                            ShortDescription = "Premium cotton kurta",
                            ShowInDealsStrip = true,
                            ShowInFlashSale = false,
                            Sku = "FI-KT-001",
                            Status = "Active",
                            Stock = 50,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "WoodCraft India",
                            CategoryId = 1,
                            Colours = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryType = "Standard (3-5 days)",
                            Description = "5 tier solid wood bookshelf for home and office.",
                            Dimensions = "",
                            FreeDelivery = true,
                            GstRate = "18",
                            HsnCode = "",
                            ImageUrls = "",
                            IncludeInAiSearch = true,
                            IsFeatured = false,
                            LowStockAlert = 5,
                            Material = "",
                            Mrp = 7500m,
                            Name = "Bookshelf 5-tier — Solid Wood",
                            Price = 5200m,
                            Rating = 4.4000000000000004,
                            ReturnPolicy = "30-day easy return",
                            ReviewCount = 76,
                            SeoTags = "bookshelf, 5 tier, wooden, storage, shelf",
                            ShortDescription = "5 tier wooden bookshelf",
                            ShowInDealsStrip = false,
                            ShowInFlashSale = false,
                            Sku = "WC-BS-001",
                            Status = "Active",
                            Stock = 20,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Warranty = "",
                            Weight = 0m
                        });
                });

            modelBuilder.Entity("ShopEase.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopEase.API.Models.Category", b =>
                {
                    b.HasOne("ShopEase.API.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShopEase.API.Models.OrderItem", b =>
                {
                    b.HasOne("ShopEase.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ShopEase.API.Models.Product", b =>
                {
                    b.HasOne("ShopEase.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopEase.API.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ShopEase.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
